autofit:
- GetDist # Cant get it to install, even in optional requirements.
- Zeus # Test Model Iniitalization no good.
- ZeusPlotter # Test Model Iniitalization no good.
- UltraNestPlotter # Test Model Iniitalization no good.
- tutorial_4_hierarchical # Can get sigma cannot be negative error due to test mode
- start_point # bug https://github.com/rhayes777/PyAutoFit/issues/1017
autogalaxy:
- tutorial_searches
- light_centre # GUI scripts cannot be run
- mask_extra_galaxies # GUI scripts cannot be run
- mask # GUI scripts cannot be run
- extra_galaxies_centres # GUI scripts cannot be run
- fits_make.py # Test mode does not output .fits images.
- png_make.py # Test mode does not output .png images.
autolens:
- tutorial_searches
- features
- tutorial_5_borders # Cant get right masks, need proper update.
- tutorial_6_model_fit # InversionException due to test mode
- extra_galaxies_centres # GUI scripts cannot be run
- mask_extra_galaxies # GUI scripts cannot be run
- lens_light_centre # GUI scripts cannot be run
- mask # GUI scripts cannot be run
- positions # GUI scripts cannot be run
- deflections # Output HDU not supported for VectorYX Detections.
- deflections_source_snr # Output HDU not supported for VectorYX Detections.
- fits_make # Test mode does not output .fits images.
- png_make # Test mode does not output .png images.
- time_delays # Test mode does not support cosmology ift
- source_reconstruction # csv file not output in test mode.
autofit_test:
- Drawer # Only works with sensitivity mapper to not raise InitializerException.
- session/general # Session mostly works but not maintaining currently.
- session/multi_analysis # Session mostly works but not maintaining currently.
autolens_test: []